# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ca854a8be8e1f13df9db7b5884ea3cde053d96a22202ed680c200460ac9f0ff405ae468f550ece5cdf32a15d713b44e82c1aed8a0062adbead733d8b3c7990

test:
  secret_key_base: 66dda9caf2386da0a9d53c10e728e2e4997bfaab009d209285bc9c87ca55b37d33728251eb18ef112cb99bf98e63bfca2b54ece69344c5365e8b55cf50ab0bec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
